repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml

-   repo: local
    hooks:
    -   id: ruff
        name: Ruff lint
        entry: uv run --no-sync ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [python, pyi]
    -   id: ruff-format
        name: Ruff format
        entry: uv run --no-sync ruff format
        language: system
        types_or: [python, pyi]
    -   id: mypy
        name: MyPy
        entry: uv run --no-sync mypy .
        language: system
        types_or: [python, pyi]
        pass_filenames: false
    -   id: mdformat
        name: Markdown format
        entry: uv run --no-sync mdformat
        language: system
        types: [markdown]

    -   id: commitlint
        name: Conventional commit message
        entry: uv run --no-sync commitlint --file
        language: system
        stages: [commit-msg]

default_language_version:
    python: python3
