name: PR Title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read

jobs:
    pr-title:
        runs-on: ubuntu-latest

        steps:
        - uses: astral-sh/setup-uv@v7
        - name: Check PR Title
          env:
            PR_TITLE: ${{ github.event.pull_request.title }}
          run: uvx --from 'commitlint>=2,<3' commitlint "$PR_TITLE"
